### ISSUE TITLE
Bug: Level integrity is not counted properly

### ISSUE THREAD

**Issue by ville-j** [elmadev/node-elma#39]
When you export a level the integrity is not counted properly (at all). This is a critical bug since it makes the level file unplayable.

**Comment by hexjelly** [comment]
I think it should be fixed if you update version to 1.0.3 now. Currently it won't check for actual integrity errors, and will just pretend every level is fine. Not sure what Elma considers errors or not yet for that. I did a very quick patch and I'm not sure if those random values work properly like this or not, but I think maybe they are fine.

I only did brief manual testing, because I started a proper TypeScript refactor, but who knows how long that will take or if ever finished at all.
